services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: vpn_db
      POSTGRES_USER: vpn_api
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vpn_api -d vpn_db -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"

  db_init:
    image: postgres:17
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./migrations/schema.sql:/schema.sql:ro
    command: >
      bash -lc "
        psql -h db -U vpn_api -d vpn_db -f /schema.sql
      "
    restart: "no"

  api:
    build: ./api
    restart: unless-stopped
    environment:
      HTTP_ADDR: ":8080"
      POSTGRES_DB: vpn_db
      POSTGRES_USER: vpn_api
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      XRAY_CONFIG_TOKEN: ${XRAY_CONFIG_TOKEN}
      XRAY_LISTEN: ${XRAY_LISTEN}
      XRAY_PORT: ${XRAY_PORT}
      XRAY_DEST: ${XRAY_DEST}
      XRAY_SERVER_NAMES: ${XRAY_SERVER_NAMES}
      XRAY_PRIVATE_KEY: ${XRAY_PRIVATE_KEY}
      XRAY_SHORT_IDS: ${XRAY_SHORT_IDS}
    depends_on:
      db_init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"

  #xray:
  #  build: ./xray
  #  restart: unless-stopped
  #  ports:
  #    - "443:443/tcp"
  #  environment:
  #    API_URL: http://api:8080/internal/xray/config
  #    AUTH_TOKEN: ${XRAY_CONFIG_TOKEN}
  #    POLL_SECONDS: "15"
  #    XRAY_CONFIG: /etc/xray/config.json
  #  volumes:
  #    - xray_state:/var/lib/xray-watcher
  #    - xray_etc:/etc/xray
  #  depends_on:
  #    api:
  #      condition: service_started

volumes:
  pg_data: {}
  xray_state: {}
 # xray_etc: {}#