services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: vpn_db
      POSTGRES_USER: vpn_api
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vpn_api -d vpn_db -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"

  db_init:
    image: postgres:17
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./migrations/schema.sql:/schema.sql:ro
    command: >
      bash -lc "
        psql -h db -U vpn_api -d vpn_db -f /schema.sql
      "
    restart: "no"

  #init_profiles:
  #  build: ./init_profiles
  #  restart: "no"
  #  environment:
  #    DB_HOST: db
  #    DB_PORT: "5432"
  #    DB_NAME: vpn_db
  #    DB_USER: vpn_api
  #    DB_PASSWORD: ${POSTGRES_PASSWORD}
  #    WATCHER_USERNAME: ${WATCHER_USERNAME}
  #    WATCHER_EMAIL: ${WATCHER_EMAIL}
  #    WATCHER_PASSWORD: ${WATCHER_PASSWORD}
  #    SUPERUSER_USERNAME: ${SUPERUSER_USERNAME}
  #    SUPERUSER_EMAIL: ${SUPERUSER_EMAIL}
  #    SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
  #  depends_on:
  #    db_init:
  #      condition: service_completed_successfully

  api:
    build: ./api
    restart: unless-stopped
    environment:
      HTTP_ADDR: ":8081"
      POSTGRES_DB: vpn_db
      POSTGRES_USER: vpn_api
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      XRAY_HOST: ${XRAY_HOST}
      XRAY_CONFIG_TOKEN: ${XRAY_CONFIG_TOKEN}
      XRAY_LISTEN: ${XRAY_LISTEN}
      XRAY_PORT: ${XRAY_PORT}
      XRAY_DEST: ${XRAY_DEST}
      XRAY_SERVER_NAMES: ${XRAY_SERVER_NAMES}
      XRAY_PRIVATE_KEY: ${XRAY_PRIVATE_KEY}
      XRAY_SHORT_IDS: ${XRAY_SHORT_IDS}
      HYSTERIA_LISTEN:  ${HYSTERIA_LISTEN}
      HYSTERIA_ACME_EMAIL: ${HYSTERIA_ACME_EMAIL}
      ACME_DOMAINS: ${ACME_DOMAINS}
      HYSTERIA_OBFS_PASSWORD: ${HYSTERIA_OBFS_PASSWORD}
      HYSTERIA_MASQUERADE_PROXY_URL: ${HYSTERIA_MASQUERADE_PROXY_URL}
      HYSTERIA_BANDWIDTH_UP: ${HYSTERIA_BANDWIDTH_UP}
      HYSTERIA_BANDWIDTH_DOWN: ${HYSTERIA_BANDWIDTH_DOWN}
    depends_on:
      db_init:
        condition: service_completed_successfully
    ports:
      - "8081:8081"
    volumes:
      - hysteria_etc:/etc/hysteria:ro

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_started

  xray_server:
    build: ./xray_server
    restart: unless-stopped
    ports:
      - "543:543/tcp"
    environment:
      WATCHER_API_URL: ${WATCHER_API_URL}
      WATCHER_EMAIL: ${WATCHER_EMAIL}
      WATCHER_PASSWORD: ${WATCHER_PASSWORD}
      WATCHER_POLL_INTERVAL: ${WATCHER_POLL_INTERVAL}
      THRESHOLD_MINUTES: ${WATCHER_THRESHOLD_MINUTES}
      WATCHER_XRAY_CONFIG_PATH: ${WATCHER_XRAY_CONFIG_PATH}
      LOGIN_ENDPOINT: /api/v1/security/login
      LAST_UPDATE_ENDPOINT: /api/v1/xray/get_last_update
      CONFIG_ENDPOINT: /api/v1/xray/config
      RESTART_COMMAND: sh -c 'test -f /tmp/xray.pid && kill $$(cat /tmp/xray.pid) || true'
    volumes:
      - xray_etc:/etc/xray
    depends_on:
      api:
        condition: service_started

  hysteria_server:
    build: ./hysteria_server
    restart: unless-stopped
    ports:
      - "643:643/udp"
    environment:
      HYSTERIA_LISTEN: ${HYSTERIA_LISTEN}
      HYSTERIA_ACME_EMAIL: ${HYSTERIA_ACME_EMAIL}
      HYSTERIA_OBFS_PASSWORD: ${HYSTERIA_OBFS_PASSWORD}
      HYSTERIA_MASQUERADE_PROXY_URL: ${HYSTERIA_MASQUERADE_PROXY_URL}
      ACME_DOMAINS: ${ACME_DOMAINS}
      WATCHER_API_URL: ${WATCHER_API_URL}
      WATCHER_EMAIL: ${WATCHER_EMAIL}
      WATCHER_PASSWORD: ${WATCHER_PASSWORD}
      WATCHER_POLL_INTERVAL: ${WATCHER_POLL_INTERVAL}
      WATCHER_HYSTERIA_CONFIG_PATH: ${WATCHER_HYSTERIA_CONFIG_PATH}
      LOGIN_ENDPOINT: /api/v1/security/login
      LAST_UPDATE_ENDPOINT: /api/v1/hysteria/get_last_update
      CONFIG_ENDPOINT: /api/v1/hysteria/config
      RESTART_COMMAND: sh -c 'test -f /tmp/hysteria.pid && kill $$(cat /tmp/hysteria.pid) || true'
    volumes:
      - hysteria_etc:/etc/hysteria
    depends_on:
      api:
        condition: service_started

volumes:
  pg_data: {}
  xray_state: {}
  xray_etc: {}
  hysteria_etc: {}
